apiVersion: v1
kind: Secret
metadata: 
    name: app-secret
type: Opaque
data:
   REDIS_PASSWORD: OWMxcmYyWWh5S3U=
   DB_PASSWORD: aGFyZGVycGFzczEyMw==
   APP_KEY: YmFzZTY0OnhwVDVZWkdtZWZ1TXFqVmlIODVxTE15cGxNR244WXhoQkVGcGMrVElKbTQ9