apiVersion: v1
kind: Service
metadata:
  labels:
    app: fance-tracking-svc
  name: fance-tracking-svc
spec:
  type: NodePort
  selector:
    app: fance-tracking
  ports:
  - name: targetport
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30007